blog/urls.py
from django.urls import path 
from .views import render_posts, post_detail

app_name = 'blog'

urlpatterns = [
	path('', render_posts, name='posts'),
	path('<int:post_id>', post_detail, name='post_detail'),
]

django_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static  
from django.conf import settings
from portfolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('blog/', include('blog.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
import datetime

class Post(models.Model):
	title = models.CharField(max_length=100)
	description = models.TextField()
	image = models.ImageField(upload_to='blog/images')
	date = models.DateField(datetime.date.today)

portfolio/models.py
from django.db import models
from django.db.models.fields import CharField, URLField
from django.db.models.fields.files import ImageField 

class Project(models.Model):
	title = CharField(max_length=100)
	description = CharField(max_length=250)
	image = ImageField(upload_to='portfolio/images/')
	url = URLField(blank=True)

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post

def render_posts(request):
	posts = Post.objects.all()
	return render(request, 'posts.html', {'posts':posts})

def post_detail(request, post_id):
	post = get_object_or_404(Post, pk=post_id)
	return render(request, 'post_detail.html', {'post':post})

portfolio/views.py
from django.shortcuts import render
from .models import Project
def home(request):
	projects = Project.objects.all()
	return render(request, 'home.html', {'projects':projects})

blog/templates/post_detail.html
{% extends 'layout.html' %}

{% block content %}

<div class="text-center">
	<h2>{{post.title}}</h2>
<h3 class="my-2 h5 text-muted">{{post.date|date:'F jS Y'}}</h3>

<img src="{{post.image.url}}" alt="{{post.title}}" class="img-fluid" />

<div class="my-4">
	<p>{{post.description|safe}}</p>
</div>
</div>

{% endblock %}

blog/templates/posts.html
{% extends 'layout.html' %}
{% block content %}
<h1>Posts</h1>

{% for post in posts %}

<div class="p-3">
	<div class="card card-body bg-black">
	<div class="row">
		<div class="col-3">
			<img src="{{post.image.url}}" alt="{{post.title}}" class="img-fluid" />
		</div>
		<div class="col-9">
			<h2>{{post.title}}</h2>
			<p>{{post.description|striptags|truncatechars:100}}</p>
			<p>{{post.date|date:'M d Y'|upper}}</p>
			<a href="{% url 'blog:post_detail' post.id %}" class="btn btn-primary">{{post.title}}</a>
		</div>
	</div>
</div>
</div>

{% endfor %}
{% endblock %}

portfolio/templates/home.html
{% extends 'layout.html' %}

{% block content %}
{% load static %}

<header class="row bg-black">
	<div class="col-md-4">
		<img src="{% static 'portfolio/profile.jpeg' %}">
	</div>
	<div class="col-md-8 my-auto">
		<h1>I am <strong>Valentín</strong></h1>
		<h3>I am a Python FullStack Developer</h3>
		<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur posuere malesuada dolor quis lobortis. Vestibulum a enim a turpis dignissim eleifend. Donec suscipit, diam et bibendum pulvinar, ex elit aliquam velit, eget porttitor velit arcu a elit. Ut aliquam metus at euismod fermentum. Sed ac sapien vehicula, elementum urna ac, rhoncus justo. Fusce vel leo id nunc consectetur auctor vel id odio. Sed a odio sed turpis bibendum porta. Quisque tincidunt aliquet dapibus. Praesent consequat, arcu sed rutrum scelerisque, felis leo consectetur lectus, ut facilisis ante erat sed ex. Aliquam erat volutpat. Duis tempus nibh id dolor fringilla pulvinar. Etiam in lacinia sapien. Vivamus hendrerit ligula in blandit tempus. Donec iaculis nisl sed dui iaculis, in pellentesque felis pulvinar.</p>
		<a href="{% static 'portfolio/Yo.jpg' %}" class="btn btn-primary btn-lg rounded-0 my-3">Download CV</a>
	</div>
</header>

<div class="row my-4 text-center">
	<h3>My projects</h3>
	<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius, illum?</p>

{% for project in projects %}

<div class="col-md-4 p-4">
	<div class="card-bg-black card-project">
		<img src="{{project.image.url}}" alt="{{project.title}}" class="card-img-top"/>
		<div class="card-body">
		<h2>{{project.title}}</h2>
		<p>{{project.description}}</p>
		{% if project.url %}
			<a href="{{project.url}}" class="btn btn-light rounded-0 btn-sm" target="_blank">{{project.url}}</a>
		{% endif %}
		</div>
	</div>
</div>	

{% endfor %}

{% endblock %}
</div>

portfolio/templates/layout.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Django Portfolio</title>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
	<link rel="stylesheet" href="{% static 'main.css' %}">
</head>
<body class="text-light">

	{% include 'partials/navbar.html' %}

	<div class="container p-4">
	{% block content %}

	{% endblock %}
	</div>
</body>
</html>

portfolio/templates/partials/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark bg-black">
  <div class="container">
    <a class="navbar-brand fw-bold fst-italic" href="/">RR</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blog:posts' %}">Blog</a>
        </li>
        <li class="nav-item d-flex align-items-center">
          <a class="btn btn-primary btn-sm" href="{% static 'portfolio/Yo.jpg' %}" target="_blank">Download CV</a>
        </li>
      </ul>
    </div>
  </div>
</nav>9ik9